#!/usr/bin/env bash

update_apt() {
  echo "Updating apt..."
  apt update || exit
  echo "Apt updated"
}

install_zsh() {
  echo "Installing zsh..."
  apt install zsh || exit

  echo "Setting zsh as default shell"
  chsh -s $(which zsh)

  echo "Installing Oh My Zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || exit

  echo "Installing zsh plugins..."
  echo "zsh-autosuggestions..."
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

  echo "zsh-syntax-highlighting..."
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

  echo "Zsh installed"
}

install_neovim() {
  echo "Installing neovim..."
  mkdir -p ~/nvim/bin || exit
  curl https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage > ~/nvim/bin/nvim || exit
  chmod +x ~/nvim/bin/nvim || exit
  echo "Neovim installed"
}

install_bat() {
  echo "Installing bat..."
  apt install bat || exit
  echo "Bat installed"
}

install_fd() {
  echo "Installing fd..."
  apt install fd-find || exit
  mkdir -p $HOME/bin || exit
  ln -s $(which fdfind) $HOME/bin/fd
  echo "Installed fd"
}

install_ripgrep() {
  echo "Installing ripgrep..."
  apt install ripgrep || exit
  echo "Installed ripgrep"
}

install_rust() {
  echo "Installing rust..."
  curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh || exit
  echo "Rust installed"
}

install_dotfiles() {
  bash <(curl -s https://raw.githubusercontent.com/mestru17/dotfiles/master/install) || exit
  git config --global core.editor "nvim"
}

install_node() {
  echo "Installing nvm..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash || exit
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  echo "Installed nvm"

  echo "Installing node..."
  nvm install node || exit
  echo "Node installed"
}

update_apt
install_zsh
install_neovim
install_bat
install_fd
install_ripgrep
install_rust
install_dotfiles
install_node

